export const KEYS = {
  ACCOUNT: 'account',
  ACCOUNTS: 'accounts',
  ROLES: 'roles',
  PERMISSION_GROUP: 'permission',
  PERMISSION_CHECK: 'permission_check',
  HRIS_POSITION: 'hris_position',
  EMPLOYEE: 'employee',
  LEAVES: 'leaves',
  CASH_ADVANCES: 'cash_advances',
  ATTENDANCE: 'attendance',
  OVERTIME: 'overtime',
  PROJECT: 'project',
  PROJECT_LABEL: 'project-label',
  CLIENT: 'client',
  CLIENT_COMPANY: 'client-company',
  GOODS: 'goods',
  TRANSACTION: 'transaction',
  SUPPLIER: 'supplier',
  SUPPLIER_EMPLOYEE: 'supplier-employee',
  BRAND: 'brand',
  CATEGORY: 'category',
  LOCATION: 'location',
  TAG: 'tag',
  MEASUREMENT: 'measurement',
  COMPETENCY: 'competency',
  KANBAN_BOARD: 'board',
}
