export const PATH = {
  BASE: '/',
  LOGIN: '/login',
  FORGOT: '/forgot',
  REGISTER: '/register',
  NOT_FOUND: '*',
  DASHBOARD_OVERVIEW: '/dashboard/overview',
  ACCOUNT: '/dashboard/accounts',
  ROLES: '/dashboard/roles',
  ROLES_PERMISSION: '/dashboard/roles-permission',
  EMPLOYEE: '/dashboard/employee',
  EMPLOYEE_DETAIL: '/dashboard/employee/:detail',
  EMPLOYEE_ADD: '/dashboard/employee/add',
  EMPLOYEE_PAID_LEAVE: '/dashboard/employee/paid-leave',
  EMPLOYEE_ATTENDANCE: '/dashboard/employee/attendance',
  EMPLOYEE_CASH_ADVANCES: '/dashboard/employee/cash-advances',
  EMPLOYEE_ATTENDANCE_SUMMARY: '/dashboard/employee/attendance/summary',

  PROJECT_INDEX: '/dashboard/project',
  PROJECT_VIEW: '/dashboard/project/view',
}
