export const keys = {
	me: 'me',
	// user: 'user',
	// userDetail: 'user-detail',
	// roles: 'roles',
	// rolesDetail: 'roles-detail',

	employee: 'employee',
	employeeInfinite: 'employee-infinite',
	employeeDetail: 'employee-detail',
	employeeSummary: 'employee-summary',
	employeeData: 'employee-data',
	employeeReportData: 'employee-report-data',
	employeeReportLastEducation: 'employee-report-last-education',

	employeeCertificates: 'employee-certificates',
	certificate: 'certificate',

	cashAdvances: 'cash_advances',
	cashAdvancesDetail: 'cash_advances-detail',
	cashAdvancesReport: 'cash_advances-report',
	cashAdvanceTransactions: 'cash_advance-transactions',

	attendance: 'attendance',
	attendanceTotalPerDay: 'attendance-total-per-day',
	attendanceReport: 'attendance-report',
	attendanceTotal: 'attendance-total',
	attendanceByDate: 'attendance-by-date',

	overtime: 'overtime',
	overtimeDetail: 'overtime-detail',
	overtimeTotalPerDay: 'overtime-total-per-day',
	overtimeReport: 'overtime-report',
	overtimeByDate: 'overtime-by-date',

	payrollPeriod: 'payroll-period',
	payrollPeriodDetail: 'payroll-period-detail',
	payrollPeriodInfinite: 'payroll-period-infinite',
	payroll: 'payroll',
	payrollDetail: 'payroll-detail',
	payrollTotal: 'payroll-total',
	payrollProgress: 'payroll-progress',

	hrisDashboardTotal: 'hris-dashboard-total',
	hrisDashboardExpireCertif: 'hris-dashboard-expire-certif',
	hrisDashboardExpireSafetyInduction: 'hris-dashboard-expire-safety',

	project: 'project',
	projectDetail: 'project-detail',
	projectEmployee: 'project-employee',
	projectAttachment: 'project-attachment',
	projectInfinite: 'project-infinite',
	projectReport: 'project-report',
	projectReportChart: 'project-report-chart',
	projectReportStatus: 'project-report-status',
	projectTotalRevenue: 'project-total-revenue',

	client: 'client',
	clientDetail: 'client-detail',
	clientInfinite: 'client-infinite',
	clientRangking: 'client-rangking',

	companyClient: 'client-company',
	companyClientInfinite: 'client-company-infinite',
	companyClientDetail: 'client-company-detail',

	supplier: 'supplier',
	supplierDetail: 'supplier-detail',
	supplierInfinite: 'supplier-infinite',
	supplierTotal: 'supplier-total',
	supplierTransaction: 'supplier-transaction',

	item: 'item',
	itemDetail: 'item-detail',
	itemInfinite: 'item-infinite',
	itemStatusChart: 'item-status-chart',
	itemLowStock: 'item-low-stock',
	itemTotal: 'item-total',
	itemSupplier: 'item-supplier',

	brand: 'brand',
	brandDetail: 'brand-detail',
	brandInfinite: 'brand-infinite',

	location: 'location',
	locationDetail: 'location-detail',
	locationInfinite: 'location-infinite',
	locationTotal: 'location-total',

	stockIn: 'stock-in',
	stockInDetail: 'stock-in-detail',
	stockOut: 'stock-out',
	stockOutDetail: 'stock-out-detail',
	stockLoan: 'stock-loan',
	stockLoanDetail: 'stock-loan-detail',
	stockLoanStatus: 'stock-loan-status',

	stockInReportByMonth: 'stock-in-report-by-month',
	stockOutReportByMonth: 'stock-out-report-by-month',

	user: 'user',
	userDetail: 'user-detail',
	userInfinite: 'user-infinite',

	ledgerChart: 'ledger-chart',
	ledgerActivity: 'ledger-activity',
}
