export const paths = {
	base: '/',
	login: '/login',
	forgot: '/forgot',
	notFound: '*',

	hris: '/hris',
	hrisMasterdataEmployee: '/hris/masterdata/employee',
	hrisMasterdataEmployeeDetail: '/hris/masterdata/employee/:id',
	hrisMasterdataEmployeeCreate: '/hris/masterdata/new-employee',
	hrisCashAdvance: '/hris/cash-advance',
	hrisCashAdvanceReport: '/hris/cash-advance/report',
	hrisAttendanceRegular: '/hris/attendance/regular',
	hrisAttendanceOvertime: '/hris/attendance/overtime',
	hrisAttendanceReport: '/hris/attendance/report',

	project: '/project',
	projectMasterdataProjects: '/project/mastedata/project',
	projectMasterdataClient: '/project/mastedata/client',
	projectMasterdataClientCompany: '/project/mastedata/company',
	projectKanban: '/project/kanban',

	inventory: '/inventory',
	inventoryMasterdataItem: '/inventory/masterdata/item',
	inventoryMasterdataLocation: '/inventory/masterdata/location',
	inventoryMasterdataBrand: '/inventory/masterdata/brand',
	inventoryMasterdataSuplier: '/inventory/masterdata/suplier',
	inventoryStockIn: '/inventory/stock/in',
	inventoryStockOut: '/inventory/stock/out',
	inventoryStockLoan: '/inventory/stock/loan',

	adminUser: '/dashboard/admin/users',
	adminRole: '/dashboard/admin/role',
	adminPermission: '/dashboard/admin/permission',
}
