export const paths = {
	base: '/',
	login: '/login',
	forgot: '/forgot',
	notFound: '*',
	account: '/account',

	hris: '/hris',
	hrisMasterdataEmployee: '/hris/masterdata/employee',
	hrisMasterdataEmployeeDetail: '/hris/masterdata/employee/:id',
	hrisMasterdataEmployeeCreate: '/hris/masterdata/new-employee',
	hrisCashAdvance: '/hris/cash-advance',
	hrisCashAdvanceDetail: '/hris/cash-advance/:id',
	hrisAttendanceRegular: '/hris/attendance/regular',
	hrisAttendanceOvertime: '/hris/attendance/overtime',
	hrisPayroll: '/hris/payroll',
	hrisPayrollDetail: '/hris/payroll/:id',
	hrisReport: '/hris/report',
	hrisSalarySlip: '/hris/salary-slip',

	project: '/project',
	projectNew: '/project/new',
	projectMasterdataProjects: '/project/masterdata/project',
	projectMasterdataProjectsDetail: '/project/masterdata/project/:id',
	projectMasterdataClient: '/project/masterdata/client',
	projectMasterdataClientDetail: '/project/masterdata/client/:id',
	projectMasterdataClientCompany: '/project/masterdata/company',
	projectMasterdataClientCompanyDetail: '/project/masterdata/company/:id',

	inventory: '/inventory',
	inventoryMasterdataItem: '/inventory/masterdata/item',
	inventoryMasterdataItemDetail: '/inventory/masterdata/item/:id',
	inventoryMasterdataLocation: '/inventory/masterdata/location',
	inventoryMasterdataLocationDetail: '/inventory/masterdata/location/:id',
	inventoryMasterdataBrand: '/inventory/masterdata/brand',
	inventoryMasterdataBrandDetail: '/inventory/masterdata/brand/:id',
	inventoryMasterdataSupplier: '/inventory/masterdata/supplier',
	inventoryMasterdataSupplierDetail: '/inventory/masterdata/supplier/:id',
	inventoryStockIn: '/inventory/stock-in',
	inventoryStockInDetail: '/inventory/stock-in/:id',
	inventoryStockInNew: '/inventory/new-stock-in',
	inventoryStockOut: '/inventory/stock-out',
	inventoryStockOutNew: '/inventory/new-stock-out',
	inventoryStockOutDetail: '/inventory/stock-out/:id',
	inventoryStockLoan: '/inventory/stock-loan',
	inventoryStockLoanNew: '/inventory/new-stock-loan',
	inventoryStockLoanDetail: '/inventory/stock-loan/:id',

	adminUser: '/admin/user',
	adminRole: '/admin/role',
	adminRoleDetail: '/admin/role/:id',
}
