name: CI-CD-STAGING
on:
  push:
    branches:
      - development
jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: "secret"
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H bjs.web.id >> ~/.ssh/known_hosts
        
      - name: Deploy to Server
        run: |
          ssh ${{ secrets.SSH_USER }}@bjs.web.id "cd /var/www/staging/frontend/ && \
          git pull origin development && \
          pnpm install && \
          pnpm build && \
          pm2 reload frontend-staging"
