name: staging
on:
  push:
    branches:
      - main
      - v2
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ./deploy.key
          sudo chmod 600 ./deploy.key
          ssh-keyscan -H erp-stg.barokahjayasemesta.com >> ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_KEY}}

      - name: Deploy to Server
        run: |
          ssh -i ./deploy.key ${{ secrets.SSH_USER }}@erp-stg.barokahjayasemesta.com "cd /app/erp-frontend-staging/ && \
          git fetch origin main && \
          git reset --hard origin/main && \
          pnpm install && \
          pnpm build && \
          pm2 reload erp-frontend-staging"
